.TH DDM-SYNC 1 "August 2026" "ddm-sync 0.1.2" "User Commands"
.SH NAME
ddm-sync \- synchronize display-manager monitor layouts
.SH SYNOPSIS
.B ddm-sync
.SH DESCRIPTION
.B ddm-sync
synchronizes the current user's display configuration with
display-manager accounts.
.PP
It uses PolicyKit for privileged operations required to update
display-manager configuration.
.SH AUTHOR
Oliver Lin